### PR TITLE
Azure virtual network

### PR DESCRIPTION
**Pull request by johnsmyth**
first attempt at virtual network - comments and suggestions welcome.

### CODE REVIEW

**Comment by stuartpreston** [comment]
This is great, @johnsmyth - any chance of adding a spec for the resource to match the others?

**Comment by johnsmyth** [comment]
I'd be happy to add some tests, but I'm not great with rspec.  Do you know of any good examples for testing chef resource attributes?

**Comment by johnsmyth** [comment]
@stuartpreston - I added some spec tests

**Comment by stuartpreston** [comment]
I have the same issue on Windows where the comparison of the label is done as if it's the only member of an array vs just the label itself. If you find an answer let me know, otherwise feel free to comment out that particular test for now and let me know when we're good to merge.

**Comment by stuartpreston** [comment]
Oh, also - could you add an example usage for this resource to README.md? Thanks!

**Comment by johnsmyth** [comment]
@stuartpreston - I commented out that test and added an example to the README.  I think you're to merge.

**Comment by johnsmyth** [comment]
Fyi - I started on azure_network_interface yesterday.  What are your thoughts on handling dependent resources?  A network interface may need a public ip, a vm will need network interfaces, etc...  

Also, what's the best forum for questions like this?

**Pull request merged**
